# Aula youtube

https://www.youtube.com/watch?v=c-NG2B1I7-Q&feature=youtu.be

In [1]:
import numpy as np

In [2]:
x = np.array([2,2,2,2])
y = np.array([4,4,4,4])

In [3]:
x + y

array([6, 6, 6, 6])

In [4]:
x - y

array([-2, -2, -2, -2])

In [5]:
y / x

array([ 2.,  2.,  2.,  2.])

In [6]:
x / y

array([ 0.5,  0.5,  0.5,  0.5])

In [7]:
x * y

array([8, 8, 8, 8])