### Aula no youtube

https://www.youtube.com/watch?v=1JnSUo3UAfM

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
type(x)

numpy.ndarray

In [4]:
x = np.linspace(0,1,10)

In [5]:
x

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [7]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
x = np.zeros(9)
x

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [10]:
x = np.ones(9)
x

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [12]:
y = x.reshape((3,3))
y

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])